services:
  frontend:
    build:
      context: .
    image: ddinovstravel-frontend:latest
    container_name: ddinovstravel-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3030}:80"
    environment:
      - "${BACKEND_API:-8010}:80"
      - "${VITE_API_URL:-api.ddinovstravel.uz}
